### ISSUE TITLE
Too light background and lost colored lights since 2.1.0

### ISSUE THREAD

**Issue by Nabawe** [adamjsx/arctis#4]
Hi first I want to say that I really like this theme but since 2.1.0 the Dark variant has become too light I include two pictures, also I noted the change to a white font which I don't know if it is a bug or that now I am required to change something.

Edit: Also since 2.1.0 the tabs zone of the UI feels too sharp 2.0.2 felt soft and confortable.

Thanks for your time.

![2 0 2](https://user-images.githubusercontent.com/11269209/167302169-d2595cab-f5d2-426b-b03a-a3bc0b102291.png)
![2 1 0](https://user-images.githubusercontent.com/11269209/167302170-78a40d9b-53d6-4a53-9105-cc16c472e1ce.png)
.

**Comment by adamdotjs** [comment]
Hi,

The background color did not change, however I did modify the other UI colors slightly for things like the editor line numbers, etc. to provide a bit more contrast to help with accessibility. What parts of it are you finding too light?

As far as the tabs, I had a request to add the borders in to help with readability, so that may be why they appear "sharper" -- If you're finding them distracting I'll certainly consider reverting that change.
